name: deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '05 22 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: actions/checkout@v2
      - uses: okteto/login@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - uses: okteto/namespace@latest
        with:
          namespace: ${{ secrets.OKTETO_NAME }}

      - name: Destroy stack
        uses: okteto/destroy-stack@main

      - name: Create stack
        uses:  okteto/deploy-stack@latest
